#!/bin/bash -xv

tmp=/tmp/$$

cat > $tmp-ps

for i in $(seq 0 1000) ; do
	grep "^$i " $tmp-ps	> $tmp-step
	[ "$(wc -l < $tmp-step)" -eq 0 ] && break

	cat $tmp-step		|
	./draw_particles 	> $i.ppm
done


rm -f $tmp-*
