#!/bin/bash
# draw_particles
# usage: cat ./sample_data/particles | ./draw_particles > particles.pgm

tmp=/tmp/$$

W=1000
H=1000

cat << FIN 
P2 $W $H 255
FIN

#world to image coordinate
gawk -v "w=$W" -v "h=$H" '{print int(w/2 + $2),int(h/2 - $3)}'	|
gawk -v "w=$W" -v "h=$H" '$1>=0 && $1<w && $2>=0 && $2<h'	|
gawk -v "w=$W" -v "h=$H" '
	{
		for(i=-1;i<2;i++)
			for(j=-1;j<2;j++)
				a[($1+i)+($2+j)*w] = 1
	}
	END{for(i=0;i<w*h;i++){print a[i]==1?0:255}}'

rm -f $tmp-*
